on:
  push:
    # Sequence of patterns matched against refs/tags
    branches: ['develop']

name: Upload Release Asset (Develop)

jobs:

  Packaging:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/nsagot/appinspect:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.TOKENPACKAGE }}

    steps:
      - uses: actions/checkout@v4

      - name: Packaging with slim
        run: slim package TA-Eventgen-Learning

      - name: Get archive name
        id: vars
        run: echo "file=" $(ls *.tar.gz) >> $GITHUB_OUTPUT

      - name: Upload AppInspect Results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.vars.outputs.file }}
          path: ${{ steps.vars.outputs.file }}
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.vars.outputs.file }}
          draft: true
          name: Latest develop